### ISSUE TITLE
Zoom issue in windows OS for Slim Viewer 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/slim#156] opened 2023-05-04 15:06 UTC
Summary - There seems to be an issue with SLIM viewer on windows OS (chrome, Edge, Firefox browsers) where SLIM viewers are not able to be zoomed. This was identified in IDC production and testing tiers. Same images can be viewed on Mac OS (Safari, chrome browsers) with no zoom issues. 

Examples of images with Zoom issue - 
https://viewer.imaging.datacommons.cancer.gov/slim/studies/2.25.317315005530798531024188637928054071011/series/1.3.6.1.4.1.5962.99.1.146852952.1107688516.1640824392792.2.0

https://viewer.imaging.datacommons.cancer.gov/slim/studies/2.25.158803907934079253044465996555538129386/series/1.3.6.1.4.1.5962.99.1.133135013.1633238587.1640810674853.2.0

https://viewer.imaging.datacommons.cancer.gov/slim/studies/2.25.142729342128247322445046799116530109403/series/1.3.6.1.4.1.5962.99.1.132828939.150100252.1640810368779.2.0

https://testing-viewer.canceridc.dev/slim/studies/2.25.273527322732788033432691536656551832061/series/1.3.6.1.4.1.5962.99.1.176549073.243901803.1640854088913.2.0

Video showing zoom issue on W10 Chrome browser (Version 112.0.5615.138 (Official Build) (32-bit)) - 
 
https://user-images.githubusercontent.com/85526819/236248840-86b161a5-0ec5-4a1e-8c87-f14f657ee34b.mp4

Video showing console with errors while opening viewer - 

https://user-images.githubusercontent.com/85526819/236249072-06dd8933-9f33-476e-9db8-75de9335a814.mp4

**Comment by hackermd** [comment] 2023-05-27 09:38
Potentially related to https://github.com/ImagingDataCommons/slim/issues/124

**Comment by igoroctaviano** [comment] 2024-11-01 18:39
Closing for now, as I couldn't reproduce the issue with the listed datasets.

**Closed by igoroctaviano** 2024-11-01 18:39 UTC
Labels: bug, idc:priority
