### ISSUE TITLE
HTAN study fails to open: "images of the image pyramid have different sizes"

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/slim#69] opened 2022-08-31 15:59 UTC
This issue was identified by @rkikinis.

https://viewer.imaging.datacommons.cancer.gov/slim/studies/2.25.174442227011591161839224535127252003551/series/1.3.6.1.4.1.5962.99.1.2352175091.700331458.1655914616819.4.0

This one does not bring up the viewer
https://imaging.datacommons.cancer.gov/explore/
htan 965

![image](https://user-images.githubusercontent.com/313942/187724565-d128980c-6b5c-4497-b7e6-eba8f78189fd.png)

**Comment by hackermd** [comment] 2022-08-31 19:13
Thanks for reporting the issue @fedorov and @rkikinis. I think this is a duplicate of https://github.com/herrmannlab/slim/issues/122. Therefore, I suggest closing this issue and tracking the problem using the existing issue in the main Slim repo.

**Closed by hackermd** 2022-08-31 19:13 UTC
Labels: bug
