### ISSUE TITLE
Getting 404 console error when I open pathology images 

### ISSUE THREAD

**Issue by VenkatPrema** [ImagingDataCommons/slim#130] opened 2022-10-26 18:23 UTC
Test Site: **ISB CGC test tier**

When I open the pathology images, No ICC profile was found for color images message appeared before loading the images.
And getting 404 console error.

![image](https://user-images.githubusercontent.com/106698935/198105728-6770f47c-fee1-4520-a0fd-9f69451f8c8a.png)

![image](https://user-images.githubusercontent.com/106698935/198105764-5b0b6763-e0ec-4f43-9210-7596a0a02c53.png)

[No ICC profile 404 console.log](https://github.com/herrmannlab/slim/files/9872701/No.ICC.profile.404.console.log)

**Comment by hackermd** [comment] 2022-10-27 12:46
Thank you for reporting the issue @VenkatPrema.

> When I open the pathology images, No ICC profile was found for color images message appeared before loading the images.

This is expected. Unfortunately, the Google Cloud Healthcare API currently doesn't provide access to ICC profiles via DICOMweb. This warning is issued to inform the user that color may not be reproducible.

> And getting 404 console error.

I cannot reproduce this error. Do you know which HTTP request resulted in a response with this status code?

**Comment by VenkatPrema** [comment] 2022-10-27 14:40
@hackermd 
**From Network tab:**
Request Method: GET
Status Code: 404 

![image](https://user-images.githubusercontent.com/106698935/198318728-3dca7927-b095-41e1-98f0-440bd6647eda.png)


[Network Response .txt](https://github.com/herrmannlab/slim/files/9880406/Network.Response.txt)

**Comment by igoroctaviano** [comment] 2024-11-05 14:44
Addressed by #249

**Closed by igoroctaviano** 2024-11-05 14:44 UTC
Labels: help wanted
